{% set name = "flake8-cognitive-complexity" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flake8_cognitive_complexity-{{ version }}.tar.gz
  sha256: f202df054e4f6ff182b659c261922b9c684628a47beb19cb0973c50d6a7831c1

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - cognitive_complexity
    - python >={{ python_min }}
    - setuptools

test:
  imports:
    - flake8_cognitive_complexity
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Melevir/flake8-cognitive-complexity
  summary: An extension for flake8 that validates cognitive functions complexity
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
